#+OPTIONS: ^:{}
* Hello!
I'm George Brooke. Maybe you know my internet username "figgyc" better.
Eventually, you can check out [[https://figgyc.uk/projects][my project portfolio]] or [[https://figgyc.uk/blog][my blog]], but I've been too busy to actually finish writing anything for them. Until then you're best looking at my [[https://github.com/figgyc?tab=repositories][GitHub repositories]].

If you want to get in touch, you can email me at ~firstname at my domain~. Are you an automated web scraper? [[mailto:inquiries@figgyc.uk][Subscribe to my spam filter ;)]]
** About me
I'm currently a student in the UK. I've been programming in some form or another for... at least 8 years? Honestly I don't even know the exact number, it feels like forever though. Most of the proper side projects I've done are for whatever internet communities I've been part of over the years.

In the future I'm hoping to become a full-time software developer. Preferably, I'd like to find a company that's making some sort of positive social difference - contributing to a better society is something I find important.

** Technologies I've used
[[https://img.shields.io/static/v1.svg?style=flat-square&label=JavaScript&logo=javascript&logoColor=black&labelColor=F7DF1E&message=Experienced&color=orange]] [[https://img.shields.io/static/v1.svg?style=flat-square&label=TypeScript&logo=typescript&logoColor=white&labelColor=3178C6&message=Experienced&color=orange]] [[https://img.shields.io/static/v1.svg?style=flat-square&label=Python&logo=python&logoColor=white&labelColor=3776AB&message=Experienced&color=orange]] [[https://img.shields.io/static/v1.svg?style=flat-square&label=Nix&logo=nixos&logoColor=white&labelColor=5277C3&message=Intermediate&color=yellow]] [[https://img.shields.io/static/v1.svg?style=flat-square&label=Svelte&logo=svelte&logoColor=white&labelColor=FF3E00&message=Beginner&color=green]]


** Things I've done recently
(This list is very incomplete)
*** [[https://figgyc.uk/projects/usercss][🖥️ figgyc's UserCSS]]
I realised that I was spending a lot of time on YouTube, so I decided to write some CSS to remove all of the addictive parts of the website. Without recommendations or notifications, I just watch new videos from my subscriptions, and move on to something else. It really improves my productivity, maybe you should try it too! I'll probably add more styles for other websites over time.
