#+OPTIONS: ^:{}
* Hello!
I'm George Brooke. Maybe you know my internet username "figgyc" better.
Check out [[https://figgyc.uk/projects][my projects]] or [[https://figgyc.uk/blog][my blog]].

If you want to get in touch, you can email me at ~firstname at my domain~. Are you an automated web scraper? [[mailto:inquiries@figgyc.uk][Subscribe to my spam filter ;)]]
** About me
I'm currently 17 and a student in the UK. I've been programming in some form or another for... at least 8 years? Honestly I don't even know the exact number, it feels like forever though. Most of the proper side projects I've done are for whatever internet communities I've been part of over the years.

In the future I'm hoping to become a full-time software developer. If I manage to mess that up I'd like to go into finance. Preferably, I'd like to find a company that's making some sort of positive social difference - contributing to a better society is something I find important.

** Technologies I've used
[[https://img.shields.io/static/v1.svg?style=flat-square&label=JavaScript&logo=javascript&logoColor=black&labelColor=F7DF1E&message=Experienced&color=orange]] [[https://img.shields.io/static/v1.svg?style=flat-square&label=TypeScript&logo=typescript&logoColor=white&labelColor=3178C6&message=Experienced&color=orange]] [[https://img.shields.io/static/v1.svg?style=flat-square&label=Python&logo=python&logoColor=white&labelColor=3776AB&message=Experienced&color=orange]] [[https://img.shields.io/static/v1.svg?style=flat-square&label=Nix&logo=nixos&logoColor=white&labelColor=5277C3&message=Intermediate&color=yellow]] [[https://img.shields.io/static/v1.svg?style=flat-square&label=Svelte&logo=svelte&logoColor=white&labelColor=FF3E00&message=Beginner&color=green]]

[[https://img.shields.io/static/v1.svg?style=flat-square&label=Emacs&logo=gnuemacs&logoColor=white&labelColor=7F5AB6&color=EEEEEE&message=is+the+better+editor+%3A%29]] (but VS Code and IntelliJ are fine too)

** My social media
(or what's left of it, I've been trying to use it less as of late)

[[https://discord.com/users/106093149381775360][https://img.shields.io/static/v1.svg?label=&message=figgyc%230168&logo=discord&logoColor=white&color=eeeeee&labelColor=5865F2&style=flat-square]]
[[https://twitter.com/f1ggyc][https://img.shields.io/static/v1.svg?label=&message=@f1ggyc&logo=twitter&logoColor=white&color=eeeeee&labelColor=1DA1F2&style=flat-square]]
[[https://github.com/figgyc][https://img.shields.io/static/v1.svg?label=&message=@figgyc&logo=github&logoColor=white&color=eeeeee&labelColor=000000&style=flat-square]]
[[https://news.ycombinator.com/user?id=figgyc][https://img.shields.io/static/v1.svg?label=&message=figgyc&logo=ycombinator&logoColor=white&color=eeeeee&labelColor=F0652F&style=flat-square]]

** Things I've done recently
*** [[https://figgyc.uk/projects/usercss][🖥️ figgyc's UserCSS]]
I realised that I was spending a lot of time on YouTube, so I decided to write some CSS to remove all of the addictive parts of the website. Without recommendations or notifications, I just watch new videos from my subscriptions, and move on to something else. It really improves my productivity, maybe you should try it too! I'll probably add more styles for other websites over time.

*** [[https://figgyc.uk/blog/document-your-projects][📝 Document your projects]]
A blog article on transparency, self-reflection and that sort of thing.
